# Generated by Django 2.1 on 2021-07-07 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pprofile',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('dp', models.ImageField(default='default.jpg', upload_to='media')),
                ('Fullname', models.CharField(max_length=255)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('Age', models.PositiveIntegerField(null=True)),
                ('Date_of_birth', models.DateField(help_text='Please Enter the following in YYYY-MM-DD')),
                ('Aadhar_number', models.CharField(max_length=12, unique=True)),
                ('Marital_status', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married'), ('Widow', 'Widow'), ('Divorce', 'Divorce')], max_length=50)),
                ('Father_name', models.CharField(max_length=255)),
                ('Father_occupation', models.CharField(max_length=255)),
                ('Father_number', models.CharField(blank=True, help_text='If minor, Please mention', max_length=10, null=True)),
                ('Mother_name', models.CharField(max_length=255)),
                ('Mother_occupation', models.CharField(max_length=255)),
                ('Guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Guardian_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('Mobile_number', models.CharField(max_length=10)),
                ('Address_1', models.CharField(max_length=900)),
                ('Address_2', models.CharField(blank=True, max_length=900, null=True)),
                ('City', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Zipcode', models.CharField(max_length=8)),
                ('Annual_income', models.PositiveIntegerField(null=True)),
                ('Caste', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=50)),
                ('Community', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christianity', 'Christianity'), ('Others', 'Others')], max_length=50)),
                ('Family_History', models.CharField(max_length=255)),
                ('Dietary_Habits', models.CharField(max_length=255)),
                ('Inter_Personal_relationship', models.CharField(max_length=255)),
                ('Health_status_of_family_members', models.CharField(blank=True, help_text='If minor, Please mention', max_length=10, null=True)),
                ('Housing_Condition', models.CharField(max_length=255)),
                ('History_of_present_illness', models.CharField(max_length=900)),
                ('History_of_past_illness', models.CharField(max_length=900)),
                ('History_of_Allergy', models.CharField(max_length=900)),
                ('Blood_Sugar', models.FloatField(blank=True, null=True)),
                ('Blood_Pressure', models.FloatField(blank=True, null=True)),
                ('Body_Temperature', models.FloatField(blank=True, null=True)),
                ('Pulse_rate', models.FloatField(blank=True, null=True)),
                ('Respiration_rate', models.FloatField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=50)),
                ('Weight', models.FloatField(blank=True, null=True)),
                ('Height', models.FloatField(blank=True, null=True)),
                ('Case_in_detail', models.TextField()),
                ('Medical_Insurance', models.CharField(max_length=900)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
