# Generated by Django 2.1 on 2021-06-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
