# Generated by Django 2.1 on 2021-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescrip', '0002_auto_20210627_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_pdf',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
