# Generated by Django 2.1 on 2021-07-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescrip', '0003_auto_20210627_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='symptoms',
            new_name='case',
        ),
    ]
