# Generated by Django 2.1 on 2021-07-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescrip', '0004_auto_20210701_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='case',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.TextField(blank=True),
        ),
    ]
