# Generated by Django 2.1 on 2021-07-01 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prescrip', '0005_auto_20210701_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
