# Generated by Django 2.1 on 2021-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescrip', '0006_auto_20210701_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
