# Generated by Django 2.1 on 2021-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_pdf',
            field=models.FileField(upload_to='prescription/med-list'),
        ),
    ]
