# Generated by Django 2.1 on 2021-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210618_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='complaints',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='foods_taken_before_consulation',
            field=models.CharField(max_length=900),
        ),
    ]
