# Generated by Django 2.1 on 2021-06-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210630_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='complaints',
            field=models.TextField(default=''),
        ),
    ]
